# Estructuras de datos: Listas


 La primera estructura de datos que veremos son las **listas**. Éstas son un conjunto de elementos ordenados separados por comas y escritos entre claudators, `[]`. 

Las listas son:
- hetereogéneas: los elementos pueden ser de distinto tipo en una misma lista
- mutables: los elementos pueden ser modificados

In [1]:
n1 = ["yakin",2,13,12.2,True]
print(n1)

['yakin', 2, 13, 12.2, True]


### Tamaño de una lista

Para saber la longitud o el tamaño de una lista, podemos hacer uso de la función `len()`

In [2]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
len(l)

9

In [3]:
l = ["Zoe", "Pablo", "Miguel", "Silvia"]
len(l)

4

Elementos de una lista
Cada elemento en la lista tiene su propio índice

In [4]:
names = ["Maria", "Juan", "Claudia", "Jorge", "Avelina"]

A `María` le corresponde el índice 0; a `Juan`, el 1; a `Claudia` el 2; a `Jorge`, el 3; y a `Avelina`, el 4.

**¡Cuidado!** En `Python`, los índices siempre empiezan en 0. De este modo, al primer elemento le corresponde el índice 0; al segundo, el índice 1; y al $n$-ésimo, le corresponde el índice $n−1$.

In [5]:
print(names[0])

Maria


In [6]:
print(names[3])

Jorge


Podemos añadir nuevos elementos a una lista con el método `.append()`


In [7]:
names = ["María", "Cristina", "Juana"]
print(names)

names.append("Andrea")
print(names)

['María', 'Cristina', 'Juana']
['María', 'Cristina', 'Juana', 'Andrea']


Si quisiéramos añadir un nuevo elemento a una lista, pero no lo quisiéramos al final, sino en una posición específica, entonces utilizaremos el método `.insert()` al que primero le indicamos el índice donde queremos posicionar el nuevo elemento y, en segundo lugar, indicamos dicho nuevo elemento.

In [8]:
names = ["Mario", "Cristian", "Juan"]
print(names)

names.insert(1, "Andrés")
print(names)
names.insert(3, "Miguel")
print(names)

['Mario', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Miguel', 'Juan']


---
## Ejercicio

Vamos a pedirle al usuario la longitud de una lista y haremos que introduzca por teclado tantos números enteros como haya indicado, que se guardarán en una lista. Al acabar, imprimiremos la lista.

In [9]:
n = int(input("Introduce el tamaño de la lista: "))
l = []

for i in range(n):
    l.append(int(input()))

print("tu lista es: ", l)

Introduce el tamaño de la lista:  5
 5 
 8
 4
 6
 21


tu lista es:  [5, 8, 4, 6, 21]


---
## Bucles con listas

In [10]:
for i in range(len(names)):
  print(names[i])

Mario
Andrés
Cristian
Miguel
Juan


In [12]:
for name in names:
  print(name)

Mario
Andrés
Cristian
Miguel
Juan


## Concatenación de listas

Dadas dos o más listas, podemos concatenarlas haciendo uso de la función `+`

In [13]:
l1 = [True, 21, "Marta"]
l2 = [22.5, False, 22, "Rafa"]
print(l1 + l2)

[True, 21, 'Marta', 22.5, False, 22, 'Rafa']


## Repetición de listas

Podemos repetir una misma lista tantas veces como queramos con la función `*`

In [14]:
abc = ["A", "B", "C"]
print(abc * 5)

['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']


## Más métodos de listas

El método `.count()` recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista

In [15]:
numbers = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]

counted = []
for element in numbers:
  if element not in counted:
    counted.append(element)
    print("El elemento {} aparece {} veces".format(element, numbers.count(element)))

El elemento 0 aparece 1 veces
El elemento 1 aparece 2 veces
El elemento 2 aparece 3 veces
El elemento 3 aparece 4 veces


El método `.extend()` extiende la lista agregando al final el iterable indicado 


In [16]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.extend([6])
print(numbers)
numbers.extend([7, 8])
print(numbers)
numbers.extend(range(9, 16))
print(numbers)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


El método `index()` recibe un elemento como argumento y devuelve el índice de la primera aparición en la lista.

In [17]:
numbers = [0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
print(numbers.index(2))
print(numbers.index(4)) 

3
7


El método `.pop()` devuelve el último elemento de la lista y lo borra de la misma.

In [18]:
print(numbers)
for i in range(5):
    print(numbers.pop())
    print(numbers)

[0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3, 4, 3]
3
[0, 1, 1, 2, 2, 2, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3]
3
[0, 1, 1, 2, 2, 2]
2
[0, 1, 1, 2, 2]


El método .remove() recibe como argumento un elemento y borra su primera aparición de la lista.



In [19]:
numbers = [0, 1, 2, 4, 3, 4, 5, 6, 7]
numbers.remove(4)
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7]


El método `.reverse()` devuelve la lista en orden inverso.

In [20]:
numbers = [1, -1, 2, -2, 3, -3]
numbers.reverse()
print(numbers)

[-3, 3, -2, 2, -1, 1]


El método `.sort()` devuelve la lista en orden. 

In [21]:
numbers = [1, 3, 5, 2, 4]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


Si quisiésemos ordenar los elementos en orden decreciente, podríamos hacer uso del parámetro `reverse` del método `.sort()`:

In [22]:
numbers = [1, 3, 5, 2, 4]
numbers.sort(reverse = True)
print(numbers)

[5, 4, 3, 2, 1]


---
# Ejercicio

Dada una lista de caracteres, le pediremos al usuario qué elemento quiere eliminar y lo eliminaremos de la lista.

In [26]:
l = ["m", "a", "r", "j", "b", "g", "i", "s", "f", "g","a"]

print("Esta es una lista original: ", l )
c = input("Introduce el elemento que deseas elimanr ")

for e in l:
    if e == c:
        l.remove(e)
    
print("Esta es  actualizada ", l)

Esta es una lista original:  ['m', 'a', 'r', 'j', 'b', 'g', 'i', 's', 'f', 'g', 'a']


Introduce el elemento que deseas elimanr  a


Esta es  actualizada  ['m', 'r', 'j', 'b', 'g', 'i', 's', 'f', 'g']


# Ejercicio

Vamos a pedir al usuario que ingrese 10 números, los guardaremos en una lista y mostraremos la lista ordenada, siendo el usuario quien indique el orden: ascendente o descendente.

In [28]:
reversed = bool(input("Si quieres orden descendente, escribe True. De lo contrario, dale a la tecla Enter: "))

l = []

for i in range(10):
    l.append(float(input()))

l.sort(reverse = reversed)
print(l)

Si quieres orden descendente, escribe True. De lo contrario, dale a la tecla Enter:  True
 8
 5
 6
 9
 1
 3
 5
 9
 4
 6


[9.0, 9.0, 8.0, 6.0, 6.0, 5.0, 5.0, 4.0, 3.0, 1.0]


## Conversión a listas

Para convertir un objeto iterable de `Python` a lista, hay que usar la función `list()`

In [29]:
print(range(0, 100, 10))

range(0, 100, 10)


In [30]:
print(type(range(0, 100, 10)))

<class 'range'>


In [31]:
print(list(range(0, 100, 10)))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [32]:
print(type(list(range(0, 100, 10))))

<class 'list'>


---
# Ejercicio

Vamos a convertir los números impares del 0 al 30 a una lista y mostrar los elementos con el fomato "El valor {} ocupa el índice {}"

In [33]:
odd = list(range(1,30,2))

for i in range(len(odd)):
    print(f"El valor {odd[i]} ocupa el indice  {i} ")

El valor 1 ocupa el indice  0 
El valor 3 ocupa el indice  1 
El valor 5 ocupa el indice  2 
El valor 7 ocupa el indice  3 
El valor 9 ocupa el indice  4 
El valor 11 ocupa el indice  5 
El valor 13 ocupa el indice  6 
El valor 15 ocupa el indice  7 
El valor 17 ocupa el indice  8 
El valor 19 ocupa el indice  9 
El valor 21 ocupa el indice  10 
El valor 23 ocupa el indice  11 
El valor 25 ocupa el indice  12 
El valor 27 ocupa el indice  13 
El valor 29 ocupa el indice  14 


--- 
## Listas anidadas

Las listas anidadas son listas dentro de listas. Es decir, las listas no solo pueden contener números, strings o datos booleanos, sino que también pueden contener otras listas.


#### Ejemplo 1

A continuación mostramos una lista anidada, pues consta de 3 elementos:

- 1 lista de 3 strings
- 1 lista heterogénea de 3 elementos que a su vez contiene una lista con 5 números
- 1 número

In [1]:
l = [["María", "Santos", "Fernández"],
     ["Juan", [1, 2, 3, 4, 5], 32], 
     2]
print(l)

[['María', 'Santos', 'Fernández'], ['Juan', [1, 2, 3, 4, 5], 32], 2]


In [2]:
print(l[0][2]) # Fernández
print(l[1][1][4]) # 5

Fernández
5


---
### Matrices

Hay un tipo muy utilizado de listas anidadas. Se caracteriza por ser una lista de $m$ listas, donde cada una de las listas tiene el mismo número de elementos, $n$. A este tipo de listas se les conoce como matrices.

In [3]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

En matemáticas, las matrices se definen del siguiente modo.

**Matriz.** Una matriz de dimensiones $m\times n$ es una tabla formada por elementos dispuestos en $m$ filas y $n$ columnas de la forma

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{pmatrix}$$

Los elementos de la matriz se representan con doble subíndice, $a_{ij}$, donde el primero indica la fila a la que pertenece y, el segundo, la columna.

Entonces, la matriz que hemos definido anteriormente

In [4]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

escrita en forma de tabla sería: `matrix` $= \displaystyle\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{pmatrix}$

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna

In [5]:
matrix[0][1]

2

In [6]:
matrix[2][2]

9

Podemos mostrar una matriz de `Python` en forma de tabla con un bucle `for`, del siguiente modo

In [7]:
for row in matrix: # Accedemos a las filas de la matrix
  print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [8]:
for row in matrix: # Accedemos a las filas
  for element in row: # Accedemos a los elementos de las filas
    print(element)

1
2
3
4
5
6
7
8
9


In [9]:
# m es el número de filas y n, el de columnas
m = len(matrix)
n = len(matrix[0])

for i in range(m):
  for j in range(n):
    print(matrix[i][j], end = " ")
  print("")

1 2 3 
4 5 6 
7 8 9 


In [10]:
for row in matrix:
  for element in row:
    print(element, end = " ")
  print("")


1 2 3 
4 5 6 
7 8 9 


---
#### Suma de matrices

Para poder sumar dos matrices, necesitamos que tengan la misma dimensión. Entonces, dadas $A$ y $B$ dos matrices con dimensión $m\times n$, su suma será una matriz de dimensión $m\times n$ y sus elementos se obtienen del siguiente modo:

$$\begin{array}{lll}A + B &=& (a_{ij})_{m\times n} + (b_{ij})_{m\times n} = (a_{ij} + b_{ij})_{m\times n}\\ 
&=&\begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} + \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1n}\\
b_{21} &b_{22} & \cdots &b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
b_{m1} &b_{m2} & \cdots & b_{mn}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\
\end{pmatrix}
\end{array}$$

Dadas dos matrices con la misma dimensión, las podemos usar haciendo uso de bucles `for` anidados.

In [15]:
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 4], [0, 2, -3]]

m = len(A)
n = len(A[0])

if len(A) == len(B) and len(A[0]) == len(B[0]):
  C = []

  for i in range(m):
    C.append([])
    for j in range(n):
      C[i].append(A[i][j] + B[i][j])

  print(C)

else:
  print("No se puede realizar la suma, pues las dimensiones de las matrices no coinciden.")

[[0, -2, -3], [0, 3, 5], [-1, 1, -3]]


In [16]:
for row in C:
  print(row)

[0, -2, -3]
[0, 3, 5]
[-1, 1, -3]


#### Producto de matrices

Para poder multiplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo número de columnas que número de filas tiene la matriz de la derecha. Entonces, dadas las matrices $A$ y $B$ de dimensiones $m\times n$ y $n\times p$ respectivamente, su producto será una matriz de dimensión $m\times p$ y se obtiene del siguiente modo:

$$\begin{array}{lll}A\cdot B &=& (a_{ij})_{m\times n}\cdot (b_{ij})_{n\times p} = \left(\sum_{k = 1}^n a_{ik}\cdot b_{kj}\right)_{m\times p}\\
&=& \begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} \cdot \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1p}\\
b_{21} &b_{22} & \cdots &b_{2p}\\
\vdots & \vdots & \ddots & \vdots\\
b_{n1} &b_{n2} & \cdots & b_{np}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11}\cdot b_{11} + a_{12} \cdot b_{21} + \cdots + a_{1n}\cdot b_{n1} & \sum_{k = 1}^n a_{1k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{1k}\cdot b_{kp}\\
a_{21}\cdot b_{11} + a_{22} \cdot b_{21} + \cdots + a_{2n}\cdot b_{n1} & \sum_{k = 1}^n a_{2k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{2k}\cdot b_{kp}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1}\cdot b_{11} + a_{m2} \cdot b_{21} + \cdots + a_{mn}\cdot b_{n1} & \sum_{k = 1}^n a_{mk}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{mk}\cdot b_{kp}
\end{pmatrix}\end{array}$$

Dadas dos matrices, la primera con el mismo número de columnas que filas tiene la segunda, podemos multiplicarlas del siguiente modo:

In [17]:
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]

m, n, p = len(A), len(B), len(B[0])

C = []

for i in range(m):
  C.append([])
  for j in range(p):
    elemento = 0
    for k in range(n):
      elemento = elemento + A[i][k] * B[k][j]
    C[i].append(elemento)

El resultado de multiplicar las matrices $A$ y $B$ ha sido

$$\begin{array}{lll} A\cdot B &=& 
\begin{pmatrix}
1 & 0 & -3 & 2\\
2 & 0 & 1 & 1\\
-1 & 0 & -1 & 0
\end{pmatrix}\cdot\begin{pmatrix}
-1 & -2 & 0\\
-2 & 3 & 0\\
0 & 0 & -3\\
1 & 1 & -1
\end{pmatrix}\\ &=& \begin{pmatrix}
1\cdot (-1) + 0\cdot (-2) -3\cdot 0 + 2\cdot 1 & 1\cdot (-2) + 0\cdot 3 -3\cdot 0 + 2\cdot 1 & 1\cdot 0 + 0\cdot 0 -3\cdot (-3) + 2\cdot (-1)\\
2\cdot (-1) + 0\cdot (-2) + 1\cdot 0 + 1\cdot 1  & 2\cdot (-2) + 0\cdot 3 + 1\cdot 0 + 1\cdot 1 & 2\cdot 0 + 0\cdot 0 + 1\cdot (-3) + 1\cdot (-1)\\
-1\cdot (-1) + 0\cdot (-2) -1\cdot 0 + 0\cdot 1  & -1\cdot (-2) + 0\cdot 3 -1\cdot 0 + 0\cdot 1 & -1\cdot 0 + 0\cdot 0 -1\cdot (-3) + 0\cdot (-1)
\end{pmatrix}\\ &=& \begin{pmatrix}
1 & 0 & 7\\
-1 & -3 & -4\\
1 & 2 & 3
\end{pmatrix}
\end{array}$$

In [19]:
for row in C:
  print(row)

[1, 0, 7]
[-1, -3, -4]
[1, 2, 3]


---
# Ejercicio

Vamos a crear manualmente una matriz de tamaño 4 x 4 y guardarla en una lista.

In [25]:
### A = []
for i in range(4):
    A.append([])
    for j in range(4):
        A[i].append(float(input(f"Introduce el elemento {i}, {j}")))
        
for i in range(4):
    for j in range(4):
        print(A[i][j], end = "  " if A[i][j] >= 0 else " ")
    print("")

Introduce el elemento 0, 0 1
Introduce el elemento 0, 1 2
Introduce el elemento 0, 2 3
Introduce el elemento 0, 3 4
Introduce el elemento 1, 0 1
Introduce el elemento 1, 1 0
Introduce el elemento 1, 2 -1
Introduce el elemento 1, 3 -2
Introduce el elemento 2, 0 -3
Introduce el elemento 2, 1 9
Introduce el elemento 2, 2 8
Introduce el elemento 2, 3 7
Introduce el elemento 3, 0 6
Introduce el elemento 3, 1 5
Introduce el elemento 3, 2 1
Introduce el elemento 3, 3 -2


1.0  2.0  1.0  2.0  
1.0  0.0  -1.0 -2.0 
-3.0 9.0  8.0  7.0  
6.0  5.0  1.0  -2.0 


Vamos a sumar dos matrices con listas. Ambas matrices serán proporcionadas por el usuario, así como la dimensión de las matrices.

In [4]:
n = int(input("Numero de filas de las matrices:"))
m = int(input("Numero de columnas de las matrices:"))

A = []
print("\n === matriz A === ")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input(f"Introduce ele elemento {i},{j}")))
        
B = []
print("\n === matriz B === ")
for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input(f"Introduce ele elemento {i},{j}")))  
        
C = []
print("\n === Suma === ")
for i in range(n):
    C.append([])
    for j in range(m):
        C[i].append(A[i][j] + B[i][j])
for i in range(n):
    for j in range(m):
        print(C[i][j], end = " " if C[i][j] >= 0 else " ")
    print("")
        


Numero de filas de las matrices: 2
Numero de columnas de las matrices: 2



 === matriz A === 


Introduce ele elemento 0,0 2
Introduce ele elemento 0,1 2
Introduce ele elemento 1,0 3
Introduce ele elemento 1,1 3



 === matriz B === 


Introduce ele elemento 0,0 5
Introduce ele elemento 0,1 5
Introduce ele elemento 1,0 6
Introduce ele elemento 1,1 6



 === Suma === 
7.0 7.0 9.0 9.0 

# Ejercicio

Vamos a calcular el producto de dos matrices con listas. Ambas matrices serán dadas por el usuario así como las dimensiones de ambas.

In [5]:
n = int(input("Número de filas de la matriz A: "))
m = int(input("Número de columnas de la matriz A: "))
p = int(input("Número de columnas de la matriz B: "))

A = []
print("\n=== Matriz A ===")
for i in range(n):
  A.append([])
  for j in range(m):
    A[i].append(float(input("Introduce el elemento ({},{}) ".format(i,j))))

B = []
print("\n=== Matriz B ===")
for i in range(m):
  B.append([])
  for j in range(p):
    B[i].append(float(input("Introduce el elemento ({},{}) ".format(i,j))))

C = []
for i in range(n):
  C.append([])
  for j in range(p):
    elemento = 0
    for k in range(m):
      elemento += A[i][k] * B[k][j]
    C[i].append(elemento)

print("\n=== Matriz A · B ===")
for i in range(n):
  for j in range(p):
    print(C[i][j], end = "  " if C[i][j] >= 0 else " ")
  print("")

Número de filas de la matriz A:  2
Número de columnas de la matriz A:  2
Número de columnas de la matriz B:  2



=== Matriz A ===


Introduce el elemento (0,0)  5
Introduce el elemento (0,1)  1
Introduce el elemento (1,0)  2
Introduce el elemento (1,1)  3



=== Matriz B ===


Introduce el elemento (0,0)  6
Introduce el elemento (0,1)  5
Introduce el elemento (1,0)  7
Introduce el elemento (1,1)  4



=== Matriz A · B ===
37.0  29.0  
33.0  22.0  


---
### Matrices con `numpy`

Existe una forma más sencilla de trabajar con matricdes y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

In [6]:
import numpy as np

In [7]:
A = np.empty((2, 3)) # 2 filas y 3 columnas
print(A)

[[6.90303559e-310 6.90303559e-310 6.90300357e-310]
 [6.90300357e-310 6.90300357e-310 6.90300357e-310]]


Para crear una matriz vacía con las mismas dimensiones de otra matriz definida anteriormente, usamos el método .empty_like(), al que le indicamos por parámetro la matriz existente

In [8]:
B = np.empty_like(A) # Tendrá 2 filas y 3 columnas
print(B)

[[6.90303559e-310 6.90303559e-310 6.90300357e-310]
 [6.90300357e-310 6.90300357e-310 6.90300357e-310]]


Para crear una matriz nula, usamos el método `.zeros()`, al que le indicamos por parámetro las dimensiones

In [12]:
C = np.zeros((3, 5)) # Matriz nula de dimensiones 3 x 5
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Para crear una matriz de ceros con las mismas dimensiones de otra matriz definida anteriormente, usamos el método .zeros_like(), al que le indicamos por parámetro la matriz existente

In [10]:
D = np.zeros_like(A) # Tendrá 2 filas y 3 columnas y todos sus elementos valdrán 0
print(D)

[[0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz de unos, usamos el método `.ones()`, al que le indicamos por parámetro las dimensiones

In [11]:
E = np.ones((1, 4)) # Matriz de unos de dimensiones 1 x 4
print(E)

[[1. 1. 1. 1.]]


Para crear una matriz de unos con las mismas dimensiones de otra matriz definida anteriormente, usamos el método .ones_like(), al que le indicamos por parámetro la matriz existente

In [13]:
F = np.ones_like(C) # Tendrá 3 filas y 5 columnas y todos sus elementos valdrán 1
print(F)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [14]:
M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
print(M)

[[ 1  0 -3  2]
 [ 2  0  1  1]
 [-1  0 -1  0]]


Para saber las dimensiones de una matriz, podemos utilizar el método `.shape`


In [15]:
M.shape

(3, 4)

Ahora es más sencillo sumar matrices, pues solamente necesitamos la función `+`

In [16]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrixSum = A + B
matrixSum

matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

También es más sencillo hacer el producto matricial $A\cdot B$ con el método `.dot()`

In [17]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrixProd = A.dot(B)
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

Gracias a `numpy`, también es mucho más sencillo mostrar una matriz en forma de tabla, pues nos basta con hacer uso de la función `print()`:

In [18]:
print(matrixSum)
print(matrixProd)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]
[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]


---
# Ejercicio

Vamos a introducir manualmente una matriz con `numpy` donde las dimensiones son proporcionadas por el usuario.

In [19]:
n = int(input("Número de filas: "))
m = int(input("Número de columnas: ")) 

A = np.empty((n, m))

for i in range(n):
  for j in range(m):
    A[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

print("\n=== Matriz A ===")
print(A)

Número de filas:  2
Número de columnas:  2
Introduce el elemento (0,0)  2
Introduce el elemento (0,1)  2
Introduce el elemento (1,0)  4
Introduce el elemento (1,1)  4



=== Matriz A ===
[[2. 2.]
 [4. 4.]]


# Ejercicio

Vamos a sumar dos matrices con `numpy`. Ambas matrices las proporcionará el usuario, así como sus dimensiones.

In [20]:
import numpy as np
n = int(input("Número de filas: "))
m = int(input("Número de columnas: "))

A = np.empty((n, m))
print("\n=== Matriz A ===")
for i in range(n):
  for j in range(m):
    A[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

B = np.empty((n, m))
print("\n=== Matriz B ===")
for i in range(n):
  for j in range(m):
    B[i, j] = float(input("Introduce el elemento ({},{}) ".format(i, j)))

print("\n=== Matriz A + B ===")
print(A + B)

Número de filas:  2
Número de columnas:  2



=== Matriz A ===


Introduce el elemento (0,0)  2
Introduce el elemento (0,1)  2
Introduce el elemento (1,0)  4
Introduce el elemento (1,1)  4



=== Matriz B ===


Introduce el elemento (0,0)  8
Introduce el elemento (0,1)  8
Introduce el elemento (1,0)  12
Introduce el elemento (1,1)  12



=== Matriz A + B ===
[[10. 10.]
 [16. 16.]]
